// src/1.app/pages/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";
import bgImage from "../../public/bg1.jpg"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-cover bg-center"
        style={{ backgroundImage: `url(${bgImage.src})` }} // Use imported image
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
